# Site settings
title: Hello World 
email: brady_smith [at] outlook.com 
description: > # this means to ignore newlines until "baseurl:"
   A record of things that I have learned. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: UnfamousBrady 
github_username: BradySmith 

# Build settings
markdown: kramdown
